Home Work 2
GumadaYaroslav/2024-01-otus-spring-gumada pull request #2
Opened 2024-02-18 17:36 UTC by GumadaYaroslav

2024-02-21 09:46 UTC, VladimirMagerov requested changes

2024-02-21 09:46 UTC, VladimirMagerov commented on hw02/src/test/java/ru/otus/hw/service/TestServiceImplTest.java
> +        assert(testResult.getRightAnswersCount() == 1);
Для проверки результатов есть намного более удобные методы, про которые подробнее можно почитать, например, вот тут:
https://www.baeldung.com/junit-assertions
Предлагаю (и рекомендую) переписать assert-ы через них, так как они избавляют нас от надобности самому составлять логическое выражение и самим писать код, который сравнивает результаты. Меньше кода пишем сами - меньше шанс ошибиться.

2024-02-21 09:46 UTC, VladimirMagerov commented on hw02/src/main/java/ru/otus/hw/config/AppProperties.java
> +        return 0;
Получается, значение из пропертей никак не используется?
![image](https://github.com/GumadaYaroslav/2024-01-otus-spring-gumada/assets/20839988/47d379a4-1548-4de0-aff0-53d421d02af4)

2024-02-23 13:26 UTC, GumadaYaroslav commented on hw02/src/test/java/ru/otus/hw/service/TestServiceImplTest.java
> +        assert(testResult.getRightAnswersCount() == 1);
поправил

2024-02-23 13:26 UTC, GumadaYaroslav commented on hw02/src/main/java/ru/otus/hw/config/AppProperties.java
> +        return 0;
поправил

2024-02-26 20:44 UTC, VladimirMagerov approved these changes

2024-02-27 20:19 UTC, merged