hw03
GumadaYaroslav/2024-01-otus-spring-gumada pull request #4
Opened 2024-02-27 20:32 UTC by GumadaYaroslav

hw03

2024-03-01 09:43 UTC, VladimirMagerov requested changes

2024-03-01 09:43 UTC, VladimirMagerov commented on hw03/src/main/java/ru/otus/hw/service/LocalizedMessagesServiceImpl.java
> +    // Доделать
Тут что-то надо доделать?)

2024-03-01 09:43 UTC, VladimirMagerov commented on hw03/src/test/java/ru/otus/hw/service/StudentServiceImplTest.java
> +class StudentServiceImplTest {
А куда пропали тесты для другого сервиса из предыдущего задания? Пусть они будут вместе)

2024-03-01 09:43 UTC, VladimirMagerov commented on hw03/src/test/java/ru/otus/hw/service/StudentServiceImplTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Wildcard импорты могут приводить к конфликту имён, предлагаю разделить на отдельные импорты.

2024-03-01 09:43 UTC, VladimirMagerov commented on hw03/src/main/java/ru/otus/hw/Application.java
> +        var testRunnerService = context.getBean(TestRunnerService.class);
Предлагаю посмотреть на специальные интерфейсы, которые в SpringBoot используются для выполнения кода при запуске приложения - https://stackoverflow.com/questions/59328583/when-and-why-do-we-need-applicationrunner-and-runner-interface
При их использовании мы снимем с себя часть ответственности и уменьшим вероятность ошибки, плюс проявим уважение к single responsibility принципу)

2024-03-03 14:08 UTC, GumadaYaroslav commented on hw03/src/main/java/ru/otus/hw/Application.java
> +        var testRunnerService = context.getBean(TestRunnerService.class);
Да, согласен! Испрвил

2024-03-03 14:08 UTC, GumadaYaroslav commented on hw03/src/main/java/ru/otus/hw/service/LocalizedMessagesServiceImpl.java
> +    // Доделать
Уже доделал, убрал

2024-03-03 14:10 UTC, GumadaYaroslav commented on hw03/src/test/java/ru/otus/hw/service/StudentServiceImplTest.java
> +class StudentServiceImplTest {
К сожалению из-за рабочей нагрузки, очень мало времени и сил заниматься курсом, а их нужно было достаточно значительно переделывать и я их удалил. Но я добавил другие, чтобы было соблюдено формальное требование на тест с моками.

2024-03-03 14:11 UTC, GumadaYaroslav commented on hw03/src/test/java/ru/otus/hw/service/StudentServiceImplTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Поправил

2024-03-05 15:12 UTC, VladimirMagerov approved these changes

2024-03-30 18:51 UTC, merged