Hw06
GumadaYaroslav/2024-01-otus-spring-gumada pull request #7
Opened 2024-08-02 23:20 UTC by GumadaYaroslav

Home work 6

2024-08-05 20:35 UTC, VladimirMagerov requested changes

2024-08-05 20:35 UTC, VladimirMagerov commented on hw06/src/main/java/ru/otus/hw/services/CommentServiceImpl.java
> +public class CommentServiceImpl implements CommentService {
При работе с комментариями всё время получается ошибочный результат:
![image](https://github.com/user-attachments/assets/a353378a-6c37-49f0-a62b-8ec95954a69e)
Предлагаю это поправить.

2024-08-06 15:49 UTC, GumadaYaroslav commented on hw06/src/main/java/ru/otus/hw/services/CommentServiceImpl.java
> +public class CommentServiceImpl implements CommentService {
исправил, это было из-за того что я использовал RequiredArgumentsConstructor не пометив переменные как final

2024-08-09 10:14 UTC, VladimirMagerov approved these changes

2024-08-09 10:47 UTC, merged